name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: |
        cd demo
        npm ci
        
    - name: Install Playwright Browsers
      run: |
        cd demo
        npx playwright install --with-deps
        
    - name: Run Playwright tests
      run: |
        cd demo
        npx playwright test
      env:
        CI: true
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: demo/playwright-report/
        retention-days: 30
